# Generated by Django 5.2 on 2025-05-13 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        max_length=8,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Code",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=128, verbose_name="Description"),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("BASIC", "Básico"),
                            ("INTERMEDIARY", "Intermediário"),
                            ("EXPERT", "Avançado"),
                        ],
                        default="BASIC",
                        max_length=16,
                        verbose_name="Level",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="Name",
                    ),
                ),
                ("rg", models.CharField(max_length=16, verbose_name="RG")),
                (
                    "cpf",
                    models.CharField(max_length=16, unique=True, verbose_name="CPF"),
                ),
                ("birthday", models.DateField(verbose_name="BDay")),
                (
                    "mobile",
                    models.CharField(default="", max_length=32, verbose_name="Mobile"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Photo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=512,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(13)],
                        verbose_name="E-mail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("MORNING", "Matutino"),
                            ("AFTERNOON", "Vespertino"),
                            ("NIGHT", "Noturno"),
                        ],
                        default="MORNING",
                        max_length=16,
                        verbose_name="Period",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school.student",
                        verbose_name="Student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
            },
        ),
    ]
