# Generated by Django 5.2 on 2025-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mobile",
            field=models.CharField(default="", max_length=32),
        ),
    ]
