# Generated by Django 5.2 on 2025-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_student_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
