# Generated by Django 5.2 on 2025-05-09 11:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_student_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Enrollment",
                "verbose_name_plural": "Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=32, null=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(
                max_length=8,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=128, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("BASIC", "Básico"),
                    ("INTERMEDIARY", "Intermediário"),
                    ("EXPERT", "Avançado"),
                ],
                default="BASIC",
                max_length=16,
                verbose_name="Level",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="period",
            field=models.CharField(
                choices=[
                    ("MORNING", "Matutino"),
                    ("AFTERNOON", "Vespertino"),
                    ("NIGHT", "Noturno"),
                ],
                default="MORNING",
                max_length=16,
                verbose_name="Period",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="school.student",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="birthday",
            field=models.DateField(verbose_name="BDay"),
        ),
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(max_length=16, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="student",
            name="mobile",
            field=models.CharField(default="", max_length=32, verbose_name="Mobile"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="rg",
            field=models.CharField(max_length=16, verbose_name="RG"),
        ),
    ]
