# Generated by Django 5.2 on 2025-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_student_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("BASIC", "Básico"),
                    ("INTERMEDIARY", "Intermediário"),
                    ("EXPERT", "Avançado"),
                ],
                default="BASIC",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="period",
            field=models.CharField(
                choices=[
                    ("MORNING", "Matutino"),
                    ("AFTERNOON", "Vespertino"),
                    ("NIGHT", "Noturno"),
                ],
                default="MORNING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="student",
            name="rg",
            field=models.CharField(max_length=16),
        ),
    ]
